service: image-resizer

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource:
            - "arn:aws:s3:::ex-4-servless-frmewrk/*"

functions:
  resize:
    handler: handler.resize
    events:
      - http:
          path: resize
          method: post
          cors: true

resources:
  Resources:
    ImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ex-4-servless-frmewrk

package:
  include:
    - node_modules/aws-sdk/**